### ISSUE TITLE
Can't send from Safari

### ISSUE THREAD

**Issue by skyjam** [hivewallet/hive-js#234]
Seems that Safari has an issue sending coins from all platforms. Get an error saying that there is no Network connection when trying to send out from the Web Wallet. 
![error](https://cloud.githubusercontent.com/assets/1421564/6318944/299da7d2-ba78-11e4-9842-248e435947be.png)

**Comment by weilu** [comment]
This is due to some CORS issue with the blockr API. We have reported a while back, and had been using a proxy server to get around it. Since we migrated to common-blockchain the proxy server has been removed. I'll put it back.

**Comment by mbz6720** [comment]
hello I am having this same problem on my hive ios wallet I also tried to send from the web wallet on my laptop and cannot send I get the same error ive emailed hive support and it has been a few days still no response

**Comment by w-hive** [comment]
@weilu Will this be solved with #237 ?

**Comment by weilu** [comment]
Let's keep it a separate issue.

**Comment by dgiffin** [comment]
I'm still having the same problem Safari 8.0.8 Mac OS X 10.10.5, not able to send any bitcoins, get a "Transaction failed Please make sure you are connected to the Internet" error.

**Comment by weilu** [comment]
@dgiffin @skyjam can you try on our staging site: https://hive-js.herokuapp.com/ and let me know if you are still having the same issue?

**Comment by dgiffin** [comment]
Wei,

That worked fine, thanks! I am slightly concerned about the lack of progress on Hive, have you considered charging micro-fees for transactions like MultiBit HD does? I prefer Hive and it would be good if you were able to continue to work on it.

    David

**Comment by weilu** [comment]
@dgiffin I apologize for the lack of progress. Unfortunately hive for me is a side project at the moment. I only get to work on it when time permits. @w-hive might be able to update you more on his future plans for Hive :)

**Comment by weilu** [comment]
Resolved.

**Comment by w-hive** [comment]
Hi @dgiffin 

We are one of the many companies/projects in the space that maybe played the game a little too optimistically in terms of Bitcoin price and our runway. ;-) Right now as Wei said, it's basically part-time. I am trying to put some more funds together for another run, but we'll see.

You can email me anytime at w@hivewallet.com if you have any questions or want to go into more detail about this.

**Comment by dgiffin** [comment]
Thank you, I fully understand your situation and wish you the best getting additional funding, Hive is a great piece of software.

  David
